// Package contextgen builds the markdown that teaches an AI agent about the
// project: `pine context` (whole-project briefing) and `pine prompt <ID>` (a
// fix request for one ticket). Output is designed to be piped into an agent.
package contextgen

import (
	"fmt"
	"strings"
	"time"

	"github.com/underworld14/pine/internal/gitx"
	"github.com/underworld14/pine/internal/store"
	"github.com/underworld14/pine/internal/ticket"
)

// Context renders a whole-project briefing. now is injectable for deterministic
// tests.
func Context(s *store.Store, git gitx.Status, now time.Time) string {
	var b strings.Builder
	cfg := s.Config()
	g := s.Graph()
	all := s.All()

	fmt.Fprintf(&b, "# Project Context: %s\n", cfg.Project.Name)
	fmt.Fprintf(&b, "> Generated by Pine · %s\n\n", now.UTC().Format(time.RFC3339))

	// Repository.
	b.WriteString("## Repository\n")
	if git.IsRepo {
		fmt.Fprintf(&b, "- Branch: `%s` · uncommitted changes: %d\n", git.Branch, len(git.Changes))
		if len(git.Changes) > 0 {
			var paths []string
			for _, c := range git.Changes {
				paths = append(paths, c.Path)
			}
			fmt.Fprintf(&b, "- Modified: %s\n", codeList(paths, 10))
		}
	} else {
		b.WriteString("- Not a git repository.\n")
	}
	b.WriteString("\n")

	if len(git.Commits) > 0 {
		b.WriteString("## Recent Commits\n")
		for _, c := range git.Commits {
			fmt.Fprintf(&b, "- `%s` %s — %s, %s\n", c.Hash, c.Subject, c.Author, c.When.Format("2006-01-02"))
		}
		b.WriteString("\n")
	}

	// Critical & high priority, open.
	var critHigh []*ticket.Ticket
	for _, t := range all {
		if t.Status != ticket.StatusDone && (t.Priority == "critical" || t.Priority == "high") {
			critHigh = append(critHigh, t)
		}
	}
	s.SortByPriorityThenUpdated(critHigh)
	if len(critHigh) > 0 {
		b.WriteString("## Critical & High Priority (open)\n")
		for _, t := range critHigh {
			fmt.Fprintf(&b, "### %s · %s · status: %s · priority: %s\n", t.ID, t.Title, t.Status, t.Priority)
			var meta []string
			if len(t.Labels) > 0 {
				meta = append(meta, "Labels: "+strings.Join(t.Labels, ", "))
			}
			if rf := ticket.RelatedFiles(t.Body); len(rf) > 0 {
				meta = append(meta, "Related files: "+strings.Join(rf, ", "))
			}
			if len(meta) > 0 {
				fmt.Fprintf(&b, "%s\n", strings.Join(meta, ". "))
			}
			if ex := excerpt(t.Body); ex != "" {
				fmt.Fprintf(&b, "> %s\n", ex)
			}
			writeAcceptanceBlock(&b, t.Body)
			b.WriteString("\n")
		}
	}

	// Ready to work.
	var ready []*ticket.Ticket
	for _, t := range all {
		if g.Ready(t.ID) {
			ready = append(ready, t)
		}
	}
	s.SortByPriorityThenUpdated(ready)
	if len(ready) > 0 {
		b.WriteString("## Ready to Work (unblocked)\n")
		writeTable(&b, ready)
		b.WriteString("\n")
	}

	// Open (not done, not testing).
	var open []*ticket.Ticket
	for _, t := range all {
		if t.Status != ticket.StatusDone && t.Status != ticket.StatusTesting && t.Prefix() != "EPIC" {
			open = append(open, t)
		}
	}
	if len(open) > 0 {
		s.SortByPriorityThenUpdated(open)
		b.WriteString("## Open Tickets\n")
		writeTable(&b, open)
		b.WriteString("\n")
	}

	// Acceptance criteria for open tickets not already detailed in crit/high.
	critHighIDs := make(map[string]bool, len(critHigh))
	for _, t := range critHigh {
		critHighIDs[t.ID] = true
	}
	var acOpen []*ticket.Ticket
	for _, t := range all {
		if t.Status == ticket.StatusDone || critHighIDs[t.ID] {
			continue
		}
		if _, total := ticket.AcceptanceProgress(t.Body); total > 0 {
			acOpen = append(acOpen, t)
		}
	}
	s.SortByPriorityThenUpdated(acOpen)
	if len(acOpen) > 0 {
		b.WriteString("## Acceptance Criteria Progress\n")
		for _, t := range acOpen {
			done, total := ticket.AcceptanceProgress(t.Body)
			fmt.Fprintf(&b, "### %s · %s (%d/%d)\n", t.ID, t.Title, done, total)
			writeAcceptanceBlock(&b, t.Body)
			b.WriteString("\n")
		}
	}

	// In testing.
	var testing []*ticket.Ticket
	for _, t := range all {
		if t.Status == ticket.StatusTesting {
			testing = append(testing, t)
		}
	}
	if len(testing) > 0 {
		b.WriteString("## In Testing\n")
		writeTable(&b, testing)
		b.WriteString("\n")
	}

	// Epics with progress.
	var epics []*ticket.Ticket
	for _, t := range all {
		if t.Prefix() == "EPIC" {
			epics = append(epics, t)
		}
	}
	if len(epics) > 0 {
		b.WriteString("## Epics\n")
		for _, e := range epics {
			done, total := g.EpicProgress(e.ID)
			fmt.Fprintf(&b, "- %s · %s (%d/%d done)\n", e.ID, e.Title, done, total)
		}
		b.WriteString("\n")
	}

	// Recently done (last 7 days).
	cutoff := now.Add(-7 * 24 * time.Hour)
	var recentDone []*ticket.Ticket
	for _, t := range all {
		if t.Status == ticket.StatusDone && t.Updated.After(cutoff) {
			recentDone = append(recentDone, t)
		}
	}
	if len(recentDone) > 0 {
		b.WriteString("## Recently Done (last 7 days)\n")
		for _, t := range recentDone {
			fmt.Fprintf(&b, "- %s %s (done %s)\n", t.ID, t.Title, t.Updated.Format("2006-01-02"))
		}
		b.WriteString("\n")
	}

	var cwdHints []string
	for _, c := range git.Changes {
		cwdHints = append(cwdHints, c.Path)
	}
	learnings, more := SelectLearnings(s, LearningSelectOpts{CwdHints: cwdHints, Limit: 10})
	if block := FormatLearningsBlock(learnings, more); block != "" {
		b.WriteString(block)
	}

	// Conventions — the part that teaches agents to write back.
	b.WriteString("## Conventions\n")
	b.WriteString("- Tickets live in `.pine/tickets/*.md` with YAML frontmatter: id, title, status, priority, labels, deps, parent.\n")
	fmt.Fprintf(&b, "- Move a ticket by editing its `status` (board columns: %s).\n", strings.Join(s.Board().Statuses(), ", "))
	b.WriteString("- `deps` lists ticket IDs that block this one; a ticket is ready when every dep is `done`.\n")
	b.WriteString("- `parent` points at an EPIC ticket for grouping.\n")
	b.WriteString("- Use `pine ready` to see actionable work, `pine close <ID>` to mark a ticket done.\n")
	b.WriteString("- Attachments live in `.pine/attachments/<ID>/` and are referenced relatively from the ticket body.\n")
	b.WriteString("- Capture durable insights with `pine learn \"...\"` into `.pine/learnings/`.\n")

	return b.String()
}

func writeTable(b *strings.Builder, ts []*ticket.Ticket) {
	b.WriteString("| ID | Title | Status | Priority | Labels |\n")
	b.WriteString("|----|-------|--------|----------|--------|\n")
	for _, t := range ts {
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n",
			t.ID, mdEscape(t.Title), t.Status, t.Priority, strings.Join(t.Labels, ", "))
	}
}

// writeAcceptanceBlock appends the AC section and checkbox progress when present.
func writeAcceptanceBlock(b *strings.Builder, body string) {
	ac, ok := ticket.SectionContent(body, "Acceptance Criteria")
	if !ok {
		return
	}
	done, total := ticket.AcceptanceProgress(body)
	if total == 0 {
		return
	}
	fmt.Fprintf(b, "\n## Acceptance Criteria (%d/%d)\n%s\n", done, total, ac)
}

// excerpt returns the first non-empty line of the Description section (or the
// body), for a one-line summary.
func excerpt(body string) string {
	src := body
	if c, ok := ticket.SectionContent(body, "Description"); ok {
		src = c
	}
	for _, ln := range strings.Split(src, "\n") {
		ln = strings.TrimSpace(ln)
		if ln != "" && !strings.HasPrefix(ln, "#") {
			return ln
		}
	}
	return ""
}

func codeList(items []string, max int) string {
	var parts []string
	for i, it := range items {
		if i >= max {
			parts = append(parts, fmt.Sprintf("… (+%d more)", len(items)-max))
			break
		}
		parts = append(parts, "`"+it+"`")
	}
	return strings.Join(parts, ", ")
}

func mdEscape(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
